### ISSUE TITLE
Suggested Feature: AM/PM to 24hs 

### ISSUE THREAD

**Issue by mtv890** [Infiziert90/ChatTwo#101]
Hi!

I would love to be able to switch timestamp from AM/PM to 24hs format

10:50 AM -> 10:50
10:50 PM -> 22:50

Not sure if this is the right place, if not please close issue.

Thanks!

**Comment by Infiziert90** [comment]
This currently depends on your local windows system settings.
Can prolly give it an hardcoded overwrite
