### ISSUE TITLE
Loss of input focus when entering a duty

### ISSUE THREAD

**Issue by acapper** [Infiziert90/ChatTwo#103]
Issue:
While you have typing focus on the chat input box when loading into a duty you lose focus of the input when the duty loading ends.
This is inconsitent with how the vanilla chat box behaves.

Expected:
Maintain focus of chat input until manual intervention eg. clicking out of the window

Replication steps (100%):
1. Enter a duty
2. While in the loading screen start typing
3. When you are able to visually see the duty chat focus will be lost will occur shortly after

Example:
https://github.com/user-attachments/assets/6982d45b-aaf2-48ee-a461-a40f92eca65e

**Comment by Infiziert90** [comment]
This should work with the new behaviour added thanks to dean
If this is still a problem, please open a new issue
