### ISSUE TITLE
Chat2 not respecting excluded channels

### ISSUE THREAD

**Issue by somnomania** [Infiziert90/ChatTwo#110]
I set my chat up at the start of DT to have shout chat not shown, to avoid spoilers. The trouble is that throughout my experience in DT, sometimes shout chat would leak through, only a couple of lines or so upon loading into a new area. And now it's just letting shout chat through all the time, despite it still being unselected for the chosen channel. I've toggled that on and off, no dice. And in vanilla chat it seems to be respecting that option, it's only Chat2 that isn't paying attention to it.

**Comment by Infiziert90** [comment]
Have you deactivated shout chat in the actual chat2 tab options?

Because it works fine on my side

**Comment by somnomania** [comment]
I haven't, no, I went through Chat2's settings and couldn't see anything that seemed like it would do that. Where are these options?

**Comment by Infiziert90** [comment]
Each Tab has a Channel header that you can open to find lots of checkboxes for all different channel types that you can find also in vanilla chat

**Comment by somnomania** [comment]
Frick. I'm blind, clearly, but we're good now, thank you!
