### ISSUE TITLE
Suggested Feature: Search function

### ISSUE THREAD

**Issue by FloralSoda** [Infiziert90/ChatTwo#111]
What I would like to see:
I would like to have a search function for the chat. It would have various filters, such as time, channel/tab, sender etc.

Use-case:
I wish to use this to check information said in chat previously, which I figure is part of the use of Chat 2. If I know a certain keyword, or the person who sent it, I could search for that and find information without having to painstakingly scroll through hours of conversation.

**Comment by Infiziert90** [comment]
/chat2Viewer already allows you to limit it to a specific date frame and search for names / content of messages
