### ISSUE TITLE
z-index with other standard UI is different from vanilla chat

### ISSUE THREAD

**Issue by xaviervv** [Infiziert90/ChatTwo#112]
When putting the inventory on top of the vanilla/original chat, the inventory (and other vanilla UI) is shown over the chat/hiding the chat, as long as the inventory has focus. When the focus is lost, then the chat is visible on over the inventory.

While with ChatTwo, the chat hides the UI all the time. Is there a setting I miss that will change this behavior back to the original?

Thank you for the great work so far.

**Comment by Infiziert90** [comment]
Chat2 uses a completely different UI framework, so anything like z-index isn't possible 

Ingame UI will always be below dalamud windows

**Comment by xaviervv** [comment]
Ok, thanks for really fast reply :D
