### ISSUE TITLE
EXP/Desynth/level gains

### ISSUE THREAD

**Issue by Faerilyn** [Infiziert90/ChatTwo#120]
I cannot see them when chat 2 is active, unless I have simply missed a check box or something, in which case I am sorry to have wasted your time, but please make these things visible. 

Level ups, exp gains, desynth gains, etc

**Comment by Infiziert90** [comment]
Go into your settings menu, Tabs, select the specific tab you want and then look through the Channel selection and you will find all of them (they don't have to be specifically named exp something, but vanilla just uses the exact same names for it's channel configuration)

**Comment by Faerilyn** [comment]
Thank you for your quick reply. Unfortunately, I have already done this. As
a test after your message, I activated every single category and every
single option to see if it is just hidden among one of the others, and
after slaying a Nzogi (70 creature) as my level 70 DRK, the only messages
regarding EXP were that a chain was sustaining.

**Comment by Infiziert90** [comment]
Check that not another plugin is blocking them, like TidyChat

**Comment by Faerilyn** [comment]
Ah, that was it, thank you. And my apologies. TidyChat was recommended by a
friend and I had forgotten about it.
