### ISSUE TITLE
Need more QoL additions

### ISSUE THREAD

**Issue by RDalcolmo** [Infiziert90/ChatTwo#124]
The following QoL would be really appreciated:

1) The ability to lock size/position from tabs that are separate from main tab
2) The ability to make specific tabs/separate tabs disappear based on a condition (In battle, in duty, etc)

**Comment by Infiziert90** [comment]
> Could also be good of it to not make itself the topmost thing on the UI, by which I mean it keeps hiding/cutting off my skill/ability tooltips when I hover over them. It's the one thing right now that's keeping me from having the plugin enabled. Regular chat lets the tooltips cover it, chat2 currently seems to cover other things instead.

Not possible, chat2 isn't native UI, just like other dalamud windows also block any Ingame UI

You can set fixed positions for your tooltips, use that option instead
