### ISSUE TITLE
[Feature Parity] Allow for Drag-selecting text

### ISSUE THREAD

**Issue by Nicolas-GE** [Infiziert90/ChatTwo#125]
the one reason i have yet to switch to chat2 is because i can't drag-select parts of previous text to copy-paste it, i'm aware the right/left clic to copy menu exists, but this copies everything, which i do not like because i need to delete parts of the text if i just want a small piece.

**Comment by Infiziert90** [comment]
This isn't easily possible thanks for to ImGui, the UI framework used by dalamud.
