### ISSUE TITLE
input for popout tab

### ISSUE THREAD

**Issue by hhharkness** [Infiziert90/ChatTwo#126]
i popped out my combat tab expecting it to get its own input field, i'm guessing the reason it didn't is an ingame limitation however there seems to be no way to "focus" the popped out tab, making the locked input channel redundant. is there any chance this is fixable, or even better - to make the input change automatically when entering/exiting a duty?
i also have the problem with the popped out tab not locking in place, saw that someone else fixed it by using dalamud window docking but for me that just makes the whole window ignore the unchecked allow movement option.

**Comment by Infiziert90** [comment]
Popouts tabs won't get their own input, just too much hassle
97a8b96326020459f5ea7ab306cc645a67626b75 added no resize and no move checkbox for popouts, so closing this as completed
