### ISSUE TITLE
Feature request: Quick channel switch keybinds

### ISSUE THREAD

**Issue by Neppkun** [Infiziert90/ChatTwo#130]
The vanilla chat has keybinds to quickly switch which channel you want your messages to be sent in.
![image](https://github.com/user-attachments/assets/80422688-90f8-43c3-9f6a-9192ea31ebd7)
These keybinds are very convenient, and ChatTwo doesn't support them. There are even players who's only reason not to use ChatTwo is because these keybinds aren't supported. So I believe it'd be a good addition if ChatTwo could react to these.

**Comment by Infiziert90** [comment]
They should be supported, i will look into it later
