### ISSUE TITLE
Feature Request: Option to revert the new change of Tell targets being remembered.

### ISSUE THREAD

**Issue by Neppkun** [Infiziert90/ChatTwo#131]
Since the 7.1 update, using the chat with quick replies have been a massive chore.

When I reply to someone with the quick reply keybind, my chat channel doesn't revert back to what it was, so I'm now required to either manually select the channel again, swap tabs twice to activate the default channel for the specific tab to be active, or use the specific command of the channel to set the channel.

Before the update, I would reply to someone, and the selected channel would switch back to what it was, and it was convenient.
This new update however, made it a massive chore to use the quick reply feature.

**Comment by Infiziert90** [comment]
I will look into it, quick reply should count as temp channel, so this is not really intended behaviour

**Comment by Infiziert90** [comment]
cb7df12005e3ccf1a6c16be0aa624520e952d462 should fix this
issues please open a new issue if this is still bugged after the update :)
