### ISSUE TITLE
[feature request] custom colours/symbols

### ISSUE THREAD

**Issue by hhharkness** [Infiziert90/ChatTwo#134]
hi! i've been looking for a way to help keep track of fc members' pronouns in the chat. currently i'm using the vanilla friend group symbols but as soon as you enter an instance they stop showing, also obviously they only work for people on your friends list. i noticed simple tweaks has an option to set different chat colours for specific users but it only seems to apply in vanilla chat, is either custom colours or symbols (or both) that apply based on character name and always show something that would be possible for you to integrate?

**Comment by Infiziert90** [comment]
The ST tweak should work just fine in chat2, i use it daily

**Comment by Infiziert90** [comment]
![image](https://github.com/user-attachments/assets/f3062c04-03f6-4ce6-a918-9bb819d9e130)

**Comment by hhharkness** [comment]
my bad, it seems the colours only apply to messages sent after the setting was changed!
