### ISSUE TITLE
Tooltip offset does not work properly

### ISSUE THREAD

**Issue by RDalcolmo** [Infiziert90/ChatTwo#135]
I got my two chat windows locked down to the bottom right of my screen. Whenever an item is linked in chat, I try to hover over it (native tooltip) and it will display behind the chats intermitently

What I tried:

All tooltip options: Next to cursor, Fixed and Fixed Reverse
All tooltip offset ranges: 0, 100, 200, 300, 400 with each option

The native tooltip still ends up behind the chats at the bottom left of my screen

**Comment by Infiziert90** [comment]
This option is only available for "Next to cursor" and only if the tooltip is generated by chat2, and works fine on my side
If your vanilla chat is still "hidden" behind chat2, it is possible that your tooltip hover is actually created by it

To go around all of that and have working tooltips regardless of type, use "Fixed" and go into your HUD Layout -> Element: Item Help -> Move it somewhere without plugin windows

**Comment by RDalcolmo** [comment]
Ahh I see, thank you. I didnt know about moving it in Fixed on HUD Layout
