### ISSUE TITLE
Chat 2 seems to at times not load

### ISSUE THREAD

**Issue by piperun** [Infiziert90/ChatTwo#18]
I wish I could provide more detailed information other than that sometimes when I boot up FFXIV it'll load just fine but othertimes Dalamud will tell me:
![image](https://github.com/Infiziert90/ChatTwo/assets/1145126/3e2cfd14-1077-4cfa-af8c-87173ff45c61)

**Comment by Infiziert90** [comment]
- Close your game
- Go to `%appdata%\XIVLauncher\pluginConfig\ChatTwo\`
- Delete the Chat2.db file

If the issue still occurs after you did, please visit the discord thread on the dalamud discord server and poke me there
(linked in the about tab too)
