### ISSUE TITLE
popped out chat windows doesnt hide

### ISSUE THREAD

**Issue by Mackersma** [Infiziert90/ChatTwo#19]
Hello,

i been noticing since the latest few updates that my popped out chat windows doesnt hide anymore in login or cut scene in the past versions this windows hide away as well

**Comment by Mackersma** [comment]
![ffxiv_dx11_XV4fCxDcVj](https://github.com/Infiziert90/ChatTwo/assets/96929292/99cdd8b0-783f-4de0-b92c-05d52b52955e)

**Comment by Infiziert90** [comment]
Known issue, haven't come around to fix it yet :)

**Comment by Mackersma** [comment]
aaah didnt aw it anyway or i been blind also a option :)

**Comment by Infiziert90** [comment]
Fixed in 91a8dd942da7c2436de4bb65127d5a04df0942f7
