### ISSUE TITLE
Sending a message to an ExtraChat LS channel (via command or tab input channel) sets the current channel to that ECLS

### ISSUE THREAD

**Issue by deansheather** [Infiziert90/ChatTwo#23]
Repro:
1. `/ecl1 message`
2. Every tab is now `ECLS [1]`

Must've been caused by some of my recent ExtraChat changes.

**Comment by thesmilingdoggo** [comment]
I am having the same issue, but it presents a bit differently.

1. Change to a Chat Tab that has a set Input Channel
2. All other tabs that do not have a set Input Channel are now set to that Input Channel.

It used to be that changing to a Channel with a Set Input Channel would only change your Input Channel while that Tab was active.

**Comment by Infiziert90** [comment]
2. Is caused by an underlying change that input channel are actually set and not just fake set

This change has happend because the fake input channels didn't work with anything vanilla, like using a macro would result in some very unexpected posting

**Comment by thesmilingdoggo** [comment]
I see, so in my case, I may need to have both an Alliance and a Party Tab if I want to avoid having to manually set my Input Channel every time I swap to a different Tab? If so, I can do that, unless you know a better way to have a Tab for both Alliance and Party Chat

**Comment by Infiziert90** [comment]
Either have two tabs or use for one of the two the / command like /p for party or /a for alliance

**Comment by thesmilingdoggo** [comment]
Ok, thank you for the quick responses!

**Comment by Infiziert90** [comment]
> I am having the same issue, but it presents a bit differently.
> 
>     1. Change to a Chat Tab that has a set Input Channel
> 
>     2. All other tabs that do not have a set Input Channel are now set to that Input Channel.
> 
> 
> It used to be that changing to a Channel with a Set Input Channel would only change your Input Channel while that Tab was active.

Changed the Behaviour in 366e121783b93aff830ed3569daec6095e945006
**New behaviour switching tabs**

- Tabs with input channel
  -  Switch to the selected channel

- Tabs without input channel
  - First time switched to this channel (current launch), they will stay at whatever channel is currently active
  - Afterwards they will remember the previous channel and restore it on switch


Is that the behaviour you would expect and be able to work with?

**Comment by thesmilingdoggo** [comment]
That is a lovely change! This way, I would need to set it to Party Chat only once instead of it going to FC every time I check my FC Tab! I thank you for this change and I hope it didn't cause any issues for you!

**Comment by deansheather** [comment]
This also fixes the behavior described in the OP.
