### ISSUE TITLE
Typing/ always doubles as //

### ISSUE THREAD

**Issue by marchenmelody** [Infiziert90/ChatTwo#24]
Whenever I press / (while I am not currently active in chat2 window), it generates a //, which makes manual emoting very difficult as I have to constantly edit.

**Comment by Infiziert90** [comment]
You have "Ready Chat" keybind set to /
Remove that keybind and everything will work as expected

**Comment by marchenmelody** [comment]
Oh my gosh, thank you, didn't realize it was a keybind!!!
