### ISSUE TITLE
Pressing enter or / when editing macros causes game to focus chat.

### ISSUE THREAD

**Issue by AlphaBraveHeart** [Infiziert90/ChatTwo#25]
I don't think this was an issue until recently, but seems like an unintended side effect to an update.

Basically title: When editing macros, pressing either the enter or forward slash key will focus Chat 2's text bar.

**Comment by Infiziert90** [comment]
You can fix the slash issue by unbinding your "Ready Command Chat" from the default /

Same for the Enter as "Ready Chat"

You don't really need any of the two as you use direct chat, else this issue wouldn't happen

**Comment by Infiziert90** [comment]
Fixed in 366e121783b93aff830ed3569daec6095e945006

**Comment by AlphaBraveHeart** [comment]
Thing is, I don't use direct chat. So that isn't the issue here.

**Comment by Infiziert90** [comment]
Switch to the newest testing version and it will be fixed, if not write here again
