### ISSUE TITLE
Chat 2 uninstalls after every game restart.

### ISSUE THREAD

**Issue by Gwiberr** [Infiziert90/ChatTwo#26]
Not sure what the root cause is but every time I restart my game, I need to reinstall Chat 2, which then fails to install and after another game restart, it is install. 

No error logs, no conflictions, no message. Not sure what is or why it is happening.

**Comment by Infiziert90** [comment]
There is some database corruption that has unknown cause and triggers to bug, but we have switched to a completely new database backend in c74d84d470d2ffce9dbcd42f384d1712388057b7 which will hopefully fix this

I aim to release this new update in dalamud testing on monday and stable the following week, so if this happens again to you after these dates, please open a new issue.

sorry for the inconvenience
