### ISSUE TITLE
Disable chat input in specific tabs

### ISSUE THREAD

**Issue by alexpado** [Infiziert90/ChatTwo#28]
Hi,
Would it be possible to have a feature allowing to disable chat completely for specific tabs ? The idea would be to hide the bottom part altogether (channel selection, text input and settings button), as few of my tabs are only notification related.

I know there is the pop-out option, but I'm starting to have less and less free space on my HUD so keeping these in tabs would be nice

**Comment by Infiziert90** [comment]
I can look into it
