### ISSUE TITLE
Cross-world friend requests not sending

### ISSUE THREAD

**Issue by WinterKnight11344** [Infiziert90/ChatTwo#32]
Any time I try to send a friend request through the right-click menu to a player in my cross-world party, it gives me "Cannot find a character with that name". I don't know if I've tested it with same-world players. Switching back to vanilla chat lets me send the request fine.

**Comment by Infiziert90** [comment]
This should be fixed thanks to e9ae8362f5eddf1cb12ce940bab9cdc1ca9ebae3
