### ISSUE TITLE
Unable to report or kick from Novice Network via right-click

### ISSUE THREAD

**Issue by samisiddiqui** [Infiziert90/ChatTwo#34]
In the regular chat, you are able to kick players from Novice Network via right clicking their name. You're also able to report players for RMT. Both of these features aren't present in Chat 2.

**Comment by Infiziert90** [comment]
I won't add them, sorry

NoviceNetwork is a huge niche, and reporting player / RTM doesn't change anything... Square bans them anyway automatically

**Comment by Infiziert90** [comment]
If you really want to report someone for anything non RTM related, use the support desk
