### ISSUE TITLE
Chat window loses focus on certain triggers

### ISSUE THREAD

**Issue by ShioIna** [Infiziert90/ChatTwo#38]
When typing in the chat the window (and text field) loses focus on certain occasions:

- entering combat
- party member entering combat
- pull timer starting
- end of duty (e.g. last boss in dugeon was killed)

Most of the time this is not a problem, but especially during occasions like raids when you are typing and someone suddenly starts a pulltimer it might cause early pulls or waste cooldowns of abilities.
I don't know if this is a setting somewhere or if this is a "dalamud thing" but I would expect the text area to stay in focus even if someone starts combat or a pull timer.

**Comment by Infiziert90** [comment]
I'm unable to reproduce this issue atm...
Could you try updating to the latest version and see if this still happens? If so, please join the dalamud discord thread for chat2 for better debugging of this issue
https://discord.com/channels/581875019861328007/1224865018789761126

**Comment by fratsch** [comment]
Ok, I will do some investigating on my end to check if this is not caused by another plugin then and will get back to you on discord!!

**Comment by Infiziert90** [comment]
1) type /xldev and press enter
2) A bar will appear on top of your game
3) GUI -> Draw metrics
4) Windows -> by focus order 
5) Enter combat/Do actions that steal focus and see what steal focus from "Chat2##chat2"

**Comment by ShioIna** [comment]
Thank you very much for the quick replies. I gather you already have taken care of "EngageTimer" and "EnmityListHP". I have notified the creators for other plugins that I identified to steal focus when they probably should not!

With this I guess this issue is closed since it is not caused by Chat2.
