### ISSUE TITLE
Feature request - Hide chat when in combat

### ISSUE THREAD

**Issue by MayakoAelys** [Infiziert90/ChatTwo#39]
Hello! :)

First, thanks for working on this plugin ❤️ My roommate loves this plugin and was very happy when he saw someone working on it again.

He asked me if it would it be possible to add a setting to automatically hide Chat2 when you're in combat with monsters / bosses? I'm not sure how hard it would be but since you're already deep in the code, it will be faster and easier for you to do it than it would be for me :3

Thanks!

**Comment by Infiziert90** [comment]
Implemented in 5d6acf7d081081d0ba6f8fb4f844c35dc29ef1ab
