### ISSUE TITLE
Allow setting an ExtraChat channel as the input channel for a tab

### ISSUE THREAD

**Issue by deansheather** [Infiziert90/ChatTwo#4]
Currently you cannot set ExtraChat channels as the input channel for a specific tab.

![image](https://github.com/Infiziert90/ChatTwo/assets/11241812/20780e7d-26be-4ca9-9f0a-8b08f551efdf)

A rudimentary way to implement this is to just add extra channel types in the channel type enums around the codebase. It doesn't let you pick a specific ExtraChat Linkshell but it lets you target a linkshell by number similarly to the in-game Linkshell options.

**Comment by deansheather** [comment]
If you're OK with it @Infiziert90 I can just contribute [this](https://github.com/deansheather/ChatThree/commit/63f92fd62ac8fb8556d8c0bb25b16ccd6a9359c0) which adds `ExtraChat Linkshell [1]` through 8.

**Comment by Infiziert90** [comment]
Can you check that this `InputChannel` never touches any of the `SetChannel` methods that interact with the game client?
Would be very weird when data gets accidentally sent to server with these as target
