### ISSUE TITLE
auto-translate shows /pet as /stroke

### ISSUE THREAD

**Issue by AthenaTaso** [Infiziert90/ChatTwo#46]
/pet and /stroke appear to autocomplete to the same value, and it always shows /stroke in the ui even when vanilla chat shows pet.
![image](https://github.com/Infiziert90/ChatTwo/assets/167266746/eddf5f06-fac7-48a7-a762-c114c420aa43)

They do however show up individually in search. You can find both /stroke and /pet in the tab complete. I acknowledge they're the same emote but... some sentences are fundamentally different with stroke than pet c:

**Comment by Infiziert90** [comment]
This issue comes from the dalamud implementation of SeStrings, so i would rather have this fixed on the side of dalamud

Informed them in the discord channel, so time to wait for now

**Comment by AthenaTaso** [comment]
Yeah, I looked through the code and figured that was the case but thought I'd let you sort it out!

Thanks for looking into it and not being lazy like me~
