### ISSUE TITLE
Where can I disable the text preview

### ISSUE THREAD

**Issue by Trelior** [Infiziert90/ChatTwo#49]
This is a feature from a newer version and I do not want it. Where can i disable it?

![image](https://github.com/Infiziert90/ChatTwo/assets/79821178/b18fcc8d-6f05-400b-86fd-a901cf465d18)

**Comment by Infiziert90** [comment]
Read the changelog that gets posted on the dalamud discord, and also appears in the plugin installer whenever you update, it explicitly tells you where the config option is located
