### ISSUE TITLE
Option to hiding Is Typing icon and chat preview.

### ISSUE THREAD

**Issue by Solidor777** [Infiziert90/ChatTwo#50]
Would really like an option to hide this.
![image](https://github.com/Infiziert90/ChatTwo/assets/14845045/81a673c3-a42e-4574-b65e-0a31f3b20d10)

**Comment by Infiziert90** [comment]
You can hide the preview, the changelog of the plugin very explicitly told how to

And for the weird A icon, no idea what that even is, never saw it

**Comment by Infiziert90** [comment]
The typing indicator comes from activate CJK IME, its not something a plugin can easily / or even at all / disable. 
This would have to be done in dalamud itself as an option, best to request it there
