### ISSUE TITLE
Group Leader Color

### ISSUE THREAD

**Issue by Colvar91** [Infiziert90/ChatTwo#60]
Hello! Is it possible to add a feature that allows you to change the color of the group leader? That would be really great if that were possible, because that's somehow missing.

**Comment by Infiziert90** [comment]
Missing? Would be new to new to me that this was supported by the game

**Comment by Colvar91** [comment]
There are actually small differences between normal Party Members and Groupleaders.

**Comment by Infiziert90** [comment]
Checked it with a color picker just now and it is the same color key
Maybe it is one of your plugin that adds the difference
