### ISSUE TITLE
No view adventure plate option

### ISSUE THREAD

**Issue by N0useforausername** [Infiziert90/ChatTwo#61]
When you right click a name in chat in the reg chat window, one of the options is view adventure plate, and it's not in the menu in the chat 2 window.

**Comment by Infiziert90** [comment]
What type of message has that happend on, and does it happen with all or just this one?

**Comment by N0useforausername** [comment]
It seems to be sporadic for emotes, either it works on both the person emoting and the person being emoted at or neither, I've had multiple instances where it doesn't work for anyone in novice network, so much so that I thought it just didn't work at all for novice, but it seems to be working today the multiple times I've checked. It works in cwls, ls, fc chat, party chat, say, yell, shout. I have not checked alliance. 

Also a completely separate thing, but I noticed while I was checking for this there is no kick from novice option in that menu, would be nice to have. 

version 1.25.3

**Comment by Infiziert90** [comment]
1.25.3 changed the behavior of this, and got released yesterday
So very likely it is fixed for now

The kick button is missing yeah, and won't be added anytime soon because it hasn't been discovered as function yet

**Comment by N0useforausername** [comment]
oh, I see, nice. any chance for playertrack integration or not likely?

**Comment by Infiziert90** [comment]
Must be done by the other side. 

Gonna close this as completed.
