### ISSUE TITLE
Wrong reaction on german keyboard Layout

### ISSUE THREAD

**Issue by Athene79** [Infiziert90/ChatTwo#62]
Hi guys.

Longer times i found a problem on the input line. Don't know if it specially happens to me because some setting of the keybinds in FF are doing this, but next I say happens...

I'm using german keyboard layout. To the right of my left Shift-Button there is a key... it contains the "Lower than" icon ( < ). Combinated by Shift its "greater than" ( > ) and using Alt+Ctrl it shows "Vertical stroke" ( | ).
If I press one of this, ChatTwo reacts not right. Different situations:
- if the chat line is not on focus and i press this button, the chatline get focus and it writes just 1 icon.
- If it is on focus and i press the button, it sends two icons, like << >> or ||. That cannot be right.
- If I write to a different plugin into a textbox (or each other kind of text input), this "object" inserts one icon, but focus switches to ChatTwo Chatline. There is no icon.

All that happens only if I turn "Direct Chat mode" on (the Checkbox on Keyboard settings in the game menu). If its off all is running fine. There will be no focus swiitch and the icons just show one time after I got focus.
I have nothing registered inGame on this Button so that there is no conflict with another function, but I need them sometimes to write this like
 `<t> <me> <flag> <pos> `
and so on and its ugly to write lines like
` <<t>> `
and so on and need to press delete button to remove the double one.
As said I don't know if this problem only is on my computer, Maybe you can try this and get the same issue. Maybe you can check this, find the problem and can fix the issue ;-) ... or you heard about the problem in past and found a solution (without turning direct chat mode off).

Thanks ;-)

**Comment by Infiziert90** [comment]
This is issue comes from how the game handles direct input and gives it to chat2

**Comment by Infiziert90** [comment]
Could you check if this bug still happens? @Athene79

**Comment by Infiziert90** [comment]
I confirmed just now that this issue is an actual problem of the UI framework and how it handles these inputs.

You can see similar behaviour with Chat2 disabled and just typing into the dalamud plugin installer search box.
Gonna close this for now, as it should be fixed in general.
