### ISSUE TITLE
Linking items, flags and similar does not work in reply mode

### ISSUE THREAD

**Issue by AlexFlipnote** [Infiziert90/ChatTwo#63]
Whenever I try to reply to someone by using the `ALT + R` shortcut, it refuses to parse `<item>` and `<flags>` at least as I have tested. However when I use them in a normal sense like party- or say chat, they do work as expected. Made a recording to highlight how it looks from my end, if it helps in any case. This was also tested on `v1.25.4.0` of the plugin, but have been an issue ever since I started using Chat2 since months ago.

https://github.com/Infiziert90/ChatTwo/assets/19587382/431822f5-278b-465a-a6a5-b3fe7158c54b

**Comment by Infiziert90** [comment]
The client resolves all text params before sending it to the server, but this function is currently unknown and not easy to find.

So this is currently not really fixable, i recommend using /r or /tell to send such text parameters
