### ISSUE TITLE
Give tooltips a horizontal offset option

### ISSUE THREAD

**Issue by Fatebreak** [Infiziert90/ChatTwo#64]
I know my situation is a bit unique, but I play across three monitors and like my chat window in the lower right corner of the leftmost screen. When I place Chat 2 here, tooltips end up getting cut between monitors because it puts the tooltip to the right of the chat window. I would love to have the option to make tooltips appear on the left side of the Chat 2 window but the current offset only moves tooltips vertically.

**Comment by Infiziert90** [comment]
You mean ImGui tooltips or? 
Because the offset is actually only for ingame tooltips to begin with, as i have no control over ImGui tooltips, they always spawn next to your mouse cursor

**Comment by Fatebreak** [comment]
Oh yes the ingame tooltips when I hover over an item link.

**Comment by Infiziert90** [comment]
Can you show an example? Because Ingame tooltips shouldn't even be able to go across screens

**Comment by Fatebreak** [comment]
Sure thing! I had to take an actual photo. ![20240531_123344.jpg](https://github.com/Infiziert90/ChatTwo/assets/77137222/b0ec969c-1aaf-44bf-a693-b274f22b1cef)

**Comment by Fatebreak** [comment]
I'm using Nvidia surround with Bezel so I suspect the game is treating all 3 monitors as one really wide monitor

**Comment by Infiziert90** [comment]
I think an easier fix for you would be fixed tooltip location, you can activate that in your character settings > UI > Tooltip location

**Comment by Fatebreak** [comment]
I didn't know that option existed! But it looks like the bezel correction I use is messing with it. Fixed position cuts it off on one bezel, and fixed reverse cuts it off the other. I had it set to Next to cursor previously. It's not an issue with the plugin though because hovering over items in my inventory creates the same problem when the setting is set to either of the Fixed options.

**Comment by Infiziert90** [comment]
You can change the fixed position in your HUD Layout, it is just a moveable element
![image](https://github.com/Infiziert90/ChatTwo/assets/22648449/3ce67c98-42b3-4660-ab31-f19af586fbcc)

**Comment by Fatebreak** [comment]
Didn't know that existed either! (It doesn't appear so long as it is set to "Next to Cursor") That did it!
