### ISSUE TITLE
Directed emotes

### ISSUE THREAD

**Issue by saraneth0o** [Infiziert90/ChatTwo#65]
Is there a way to add a filter so it only show my emotes and emotes directed at me, but filter all other emotes?

**Comment by Infiziert90** [comment]
With emotes you mean /em and /hug...........?
If so, use a plugin like TidyChat with filter rules

**Comment by saraneth0o** [comment]
> With emotes you mean /em and /hug...........? If so, use a plugin like TidyChat with filter rules

Thanks. Looks like there is a setting for that in TidyChat :)
