### ISSUE TITLE
Debuff linking

### ISSUE THREAD

**Issue by Nelayaya** [Infiziert90/ChatTwo#66]
Hello ! Sorry if I just suck at using your plugin but I believe it's not possible to link a debuff from combat log in such way that your party members can mouseover on it and see the details as you can do in the vanilla chat ? If it's not just me and the plugin doesn't do this, it would be an amazing addition !

**Comment by Infiziert90** [comment]
It is currently not possible in chat2, correct

The priority for such a feature is quite low as it is alot of work, so maybe after DT has fully arrived

**Comment by Nelayaya** [comment]
Good to know you're thinking about it already ! Thanks for the super good plugin ♥

**Comment by Infiziert90** [comment]
Keeping this open for tracking reasons
