### ISSUE TITLE
Manifest broken

### ISSUE THREAD

**Issue by TheCrimsonSpark** [Infiziert90/ChatTwo#67]
Upon updating the plugin in dalamud, it "uninstalled" itself, and presents the "failed to install plugin" error. Upon relaunch "plugin failed to load"

**Comment by dumbusernameidk** [comment]
Same issue here.

**Comment by axium1998** [comment]
I noticed there's a "fix for now" branch, but I have no idea how to use it instead of the normal one

**Comment by Infiziert90** [comment]
> Dalamud will receive an update in some minutes, 
> restart your game after that update has dropped and 
> everything should work again
