### ISSUE TITLE
Broken Reply-To-Last

### ISSUE THREAD

**Issue by Kuroshiro2573** [Infiziert90/ChatTwo#68]
When using the Reply-To-Last keybind, the server the character is shown as being from will always say Dev, and messages will not go through unless right-clicking on the character's name and messaging manually.

**Comment by AlexFlipnote** [comment]
Can confirm, recorded a GIF for demonstration

![ffxiv_dx11_2024-06-11_01-25-50](https://github.com/Infiziert90/ChatTwo/assets/19587382/ba206512-a4ae-4429-88de-5119c9021998)

**Comment by Infiziert90** [comment]
Already fixed in 17ff8ff
