### ISSUE TITLE
Add regex filtering for incoming messages

### ISSUE THREAD

**Issue by deansheather** [Infiziert90/ChatTwo#69]
Add an advanced option that lets users set one or more regex filters on each incoming message. If a message matches, it will be blocked.

Also allow users to set which chat types it applies to.

E.g.

`/^Triple triad matches allowed in the current area.$/` (System Messages)

**Comment by Infiziert90** [comment]
If people want that, they should just use other plugins like NoSol or TidyChat, which even has pre configured exclusion for most annoying things
