### ISSUE TITLE
Tooltips visible over ChatTwo window

### ISSUE THREAD

**Issue by FreeAura** [Infiziert90/ChatTwo#72]
Hey, not really an issue report more of a question to see if it's possible to make vanilla tooltips take priority over the ChatTwo window? With positioning of Hotbars it makes them difficult to read as they're behind the window. Example attached.

![Screenshot_1](https://github.com/Infiziert90/ChatTwo/assets/126380561/e7446d5e-43d0-425f-9438-b5b3ffffd55c)

**Comment by Infiziert90** [comment]
This isn't possible with ImGui
