### ISSUE TITLE
Chat2 Linkshell swap priority

### ISSUE THREAD

**Issue by bongbong508** [Infiziert90/ChatTwo#75]
Hello,

This used to not be an issue long ago, though I haven't played in a while so it's different now.

I have my keybinds to switch Linkshell channels on my Numpad, so LS1 on 1, LS2 on 2, etc. 

However, when I'm for example on my retainer, trying to put in a price for an Item I want to sell, I usually use the numpad, which does not work with chat2 anymore, as it instead goes into the swapped channel now instead of typing the price. This isn't an issue with default chat and to my memory used to not be an issue with chat2 either. I couldn't find a setting to disable this either.

Any way this could be fixed/changed?

Thank you

**Comment by Infiziert90** [comment]
Keybinds didn't work before in chat2, now they do

It should prevent that with a check if any input box in vanilla chat is active, but maybe the offset for that broke

**Comment by Infiziert90** [comment]
Should be fixed now
