### ISSUE TITLE
/cl (clear chat command) doesn't clear Chat2 chat log.

### ISSUE THREAD

**Issue by ltsLumina** [Infiziert90/ChatTwo#78]
The "/cl" command clears the entire chat log with the default chat, but does nothing with Chat2. I'd appreciate if it cleared Chat2 also 👍 
![clear command doesnt work](https://github.com/Infiziert90/ChatTwo/assets/119983088/0e247e08-05a4-4045-986a-1358f1e19bf0)

**Comment by Infiziert90** [comment]
Chat2 has /clearlog2 and you can even clear only specific tabs

**Comment by ltsLumina** [comment]
Was not aware of this, thank you!
