### ISSUE TITLE
Tell Unable to Send While in Instance

### ISSUE THREAD

**Issue by EdwardShipp** [Infiziert90/ChatTwo#81]
When attempting to send a tell, such as by right click send tell, the text will turn pink to imply that it is going to send as tell but send the following error:
To use that command, you must add the World name to the PC name (PC Name@World Name).

Tell works normally while outside of instances

**Comment by Infiziert90** [comment]
You can't tell in instance, that never worked nor does vanilla chat work

The only exceptions are bozja and eureka

**Comment by EdwardShipp** [comment]
Oh, I forgot that was a specific limitation. This was in Eureka that I was receiving the error messages, so I'm not sure why vanilla chat would work but not a tell in chat2. I just spend most of my time there I forgot other instances weren't able to use tell in.
