### ISSUE TITLE
Request: Adjust Frame Strata

### ISSUE THREAD

**Issue by meltryllis-git** [Infiziert90/ChatTwo#91]
Hello, love this plugin! I just have one gripe: the chat window frame strata appears to have high priority and is on top of UI elements, notably tooltips in my experience.

Very minor gripe, but I thought I'd ask anyway.

**Comment by Infiziert90** [comment]
It's impossible with dalamud windows, even clipping it (making the area disappear that chat2 would cover, isn't possible as imgui doesn't allow that for windows like chat2)
