### ISSUE TITLE
Blurred letters in settings and chat.

### ISSUE THREAD

**Issue by Azarovalina** [Infiziert90/ChatTwo#96]
It seems as if I had changed the resolution only of the settings window and the chat, everything looks blurry.
![imagen](https://github.com/user-attachments/assets/aa7c641c-25d4-4769-90e9-9d445d96ee86)
Compare the font on the left with the two windows on the right. There should be a button to reset settings, and if there is, I don't see where it is.

**Comment by Infiziert90** [comment]
Your issue is actually using the default font (custom font checkbox unchecked) and a font size that isn't compatible with it

Axis Font, the ffxiv font only supports some specific sizes, 9.
