### ISSUE TITLE
Feature request: text drop shadow

### ISSUE THREAD

**Issue by bashemi** [Infiziert90/ChatTwo#97]
Possible to add a drop shadow (or at least an option for it) to the text in the chat window? Would increase readability at increased transparency. 
![C2](https://github.com/user-attachments/assets/89e9fb56-e0f7-488f-b22b-73960fab0cfc)
Example of the stock UI:
![image](https://github.com/user-attachments/assets/5a8e203d-67ad-4913-889d-b5e751bf0f36)

**Comment by Infiziert90** [comment]
Not really possible with ImGui, it would increase the performance requirements by miles and code wise would be an absolute nightmare
